name: Pull request rules

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Branch up-to-date rule
        run: |
          git fetch origin
          devBranch=${{ github.event.pull_request.base.ref }}
          requestedBranch=${{ github.event.pull_request.head.ref }}
          if [ "$devBranch" != "$requestedBranch" ]; then
            echo "Requested branch is not up-to-date"
            exit 1
          fi
  
  enforce-pr-title:
    name: Enforce PR title
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const REGEX = RegExp("([A-Z]{2,3}-\\d{1,5})\\s?(.+)");
 
          const { title } = context.payload.pull_request;
          
          if (!REGEX.test(title)) {
            core.setFailed(
              `Pull Request title "${title}" failed to match regex - ${REGEX}`
            );
            return;
          }