name: Pull request rules

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Branch up-to-date rule
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.head.ref }}
          if git merge-base --is-ancestor origin/${{ github.event.pull_request.base.ref }} HEAD; then
            echo "Pull request branch is up to date with target branch."
          else
            echo "Pull request branch is behind the target branch. Please update your branch."
            exit 1
          fi
  
  enforce-pr-title:
    name: Enforce PR title
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const REGEX = RegExp("([A-Z]{2,3}-\\d{1,5})\\s?(.+)");
 
          const { title } = context.payload.pull_request;
          
          if (!REGEX.test(title)) {
            core.setFailed(
              `Pull Request title "${title}" failed to match regex - ${REGEX}`
            );
            return;
          }